apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: ch_infinite_streaming
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: infinite_streaming
      tlsSkipVerify: true
      username: default
    secureJsonData:
      password: ""
    editable: true
