package util

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

type ByterangeResult struct {
	Success          bool     `json:"success"`
	ContentName      string   `json:"content_name"`
	TotalSegments    int      `json:"total_segments"`
	Processed        int      `json:"processed"`
	Failed           int      `json:"failed"`
	FailedFiles      []string `json:"failed_files"`
	ByterangesCount  int      `json:"byteranges_generated"`
	Message          string   `json:"message"`
}

func GenerateByteranges(segments []string, contentRoot, contentName string) ByterangeResult {
	result := ByterangeResult{
		Success:       true,
		ContentName:   contentName,
		TotalSegments: len(segments),
		FailedFiles:   []string{},
	}
	for _, segment := range segments {
		trackType := "video"
		if strings.Contains(segment, string(filepath.Separator)+"audio"+string(filepath.Separator)) {
			trackType = "audio"
		}
		cmd := exec.Command("python3", "/sbin/parse_fmp4_fragments.py", "--track-type", trackType, segment)
		cmd.Stdout = nil
		cmd.Stderr = nil
		err := runWithTimeout(cmd, 10*time.Second)
		if err != nil {
			result.Failed++
			rel, _ := filepath.Rel(contentRoot, segment)
			result.FailedFiles = append(result.FailedFiles, rel)
			result.Success = false
			continue
		}
		result.Processed++
	}
	count := 0
	_ = filepath.WalkDir(contentRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			return nil
		}
		if strings.HasSuffix(path, ".byteranges") {
			count++
		}
		return nil
	})
	result.ByterangesCount = count
	result.Message = "Generated byteranges"
	return result
}

func runWithTimeout(cmd *exec.Cmd, timeout time.Duration) error {
	if err := cmd.Start(); err != nil {
		return err
	}
	done := make(chan error, 1)
	go func() {
		done <- cmd.Wait()
	}()
	select {
	case err := <-done:
		return err
	case <-time.After(timeout):
		_ = cmd.Process.Kill()
		return Errf("timeout")
	}
}
