// AUTO-GENERATED by Xcode build phase "Sync version from repo VERSION".
// DO NOT EDIT — overwritten on every build from the repo-root VERSION.
// To bump the version, edit /VERSION at the repo root.
enum AppVersionGenerated {
    static let value: String = "2.0.0"
}
